# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/skeleton.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from _enigma import Enigma


class Ui_MainWindow(object):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.enigma = Enigma()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(839, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.position_label = QtWidgets.QLabel(self.frame_2)
        self.position_label.setObjectName("position_label")
        self.horizontalLayout.addWidget(self.position_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.reset_button = QtWidgets.QPushButton(self.frame_2)
        self.reset_button.setObjectName("reset_button")
        self.verticalLayout_4.addWidget(self.reset_button)
        self.encrypt_button = QtWidgets.QPushButton(self.frame_2)
        self.encrypt_button.setObjectName("encrypt_button")
        self.verticalLayout_4.addWidget(self.encrypt_button)
        self.verticalLayout_2.addWidget(self.frame_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.input_field = QtWidgets.QPlainTextEdit(self.frame)
        self.input_field.setObjectName("input_field")
        self.verticalLayout_2.addWidget(self.input_field)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.output_field = QtWidgets.QPlainTextEdit(self.frame)
        self.output_field.setObjectName("output_field")
        self.verticalLayout_2.addWidget(self.output_field)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.setup_logic()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Enigma emulator"))
        self.label_4.setText(_translate("MainWindow", "Current rotor positions:"))
        self.position_label.setText(_translate("MainWindow", "A-A-A"))
        self.reset_button.setText(_translate("MainWindow", "RESET"))
        self.encrypt_button.setText(_translate("MainWindow", "ENCRYPT"))
        self.label.setText(_translate("MainWindow", "Input"))
        self.label_2.setText(_translate("MainWindow", "Output"))

    def setup_logic(self):
        self.encrypt_button.clicked.connect(self.encrypt)
        self.reset_button.clicked.connect(self.reset)

    def encrypt(self):
        self.output_field.setPlainText(self.enigma.encrypt(self.input_field.toPlainText()))
        self.update_enigma_state()

    def update_enigma_state(self):
        self.position_label.setText("-".join(self.enigma.current_state))

    def reset(self):
        self.enigma = Enigma()
        self.update_enigma_state()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
